name: Build pi4j-kotlin

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: build project
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew lib:check
