name: Release pi4j-kotlin

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: release project
        env:
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET }}
          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          ./gradlew build
          ORG_GRADLE_PROJECT_sonatypeUsername=TODO ORG_GRADLE_PROJECT_sonatypePassword=TODO ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository